version: 1
default_environment: prod
send_anonymous_usage_stats: true
project_id: 7719d6c0-e1ea-45f2-85e4-a647da2211dd
plugins:
  extractors:
  - name: tap-lastfm
    namespace: tap_lastfm
    pip_url: git+https://github.com/rabidaudio/tap-lastfm.git@v0.1.1
    executable: tap-lastfm
    capabilities:
    - catalog
    - discover
    - state
    settings:
    - name: api_key
      kind: password
    - name: usernames
      kind: array
    - name: user_agent
      kind: string
    - name: start_date
      kind: date_iso8601
    config:
      api_key: $TAP_LASTFM_API_KEY
      usernames:
      - rabidaudio
      - kath_ebooks
      - valwigg
      - UntiLiUnderstan
      - trackstarlol
      - schwegler
      - emorphis
    select:
    - '*.*'
    - '!*.*image*'
  - name: tap-lichess
    namespace: tap_lichess
    pip_url: git+https://github.com/rabidaudio/tap-lichess.git@v1.0.1
    executable: tap-lichess
    capabilities:
    - catalog
    - discover
    - state
    settings:
    - name: auth_token
      kind: password
    - name: usernames
      kind: array
    config:
      usernames:
      - charlesjuliank
      - chuckbruckus
      - MaksimSundukov
      - LivAgar
      - Tom_Ripley
  loaders:
  - name: target-athena
    variant: meltanolabs
    pip_url: git+https://github.com/rabidaudio/target-athena.git@80d29af
    config:
      s3_bucket: audio-rabid-selfdata
      athena_database: $MELTANO_EXTRACTOR_NAMESPACE
      aws_region: us-east-1
      add_record_metadata: true
      object_format: jsonl
      compression: gzip
      s3_staging_dir: s3://audio-rabid-selfdata/_staging
      partition_keys:
        dt: date(row['_sdc_extracted_at'])
  transformers:
  - name: dbt-athena
    inherit_from: dbt
    pip_url: dbt-core~=1.0.0 dbt-athena-adapter~=1.0.1
    commands:
      generate-source: run-operation generate_source --args ''{"schema_name":"$MELTANO_LOAD_SCHEMA","generate_columns":true}''
      test-freshness: source freshness
  utilities:
  - name: dagster
    namespace: dagster
    pip_url: -e orchestrate
    executable: dagster
    settings:
    - name: home
      env: DAGSTER_HOME
    - name: schedule_timezone
      env: DAGSTER_SCHEDULE_TIMEZONE
    - name: database_url
      env: DAGSTERDB_URL
    commands:
      scheduler:
        args: run -w $DAGSTER_HOME/workspace.yaml
        executable: dagster-daemon
      ui:
        args: -w $DAGSTER_HOME/workspace.yaml -h 0.0.0.0
        executable: dagit
      test:
        args: -v
        executable: pytest
    config:
      schedule_timezone: America/New_York
      database_url: $DAGSTERDB_URL
      home: $MELTANO_PROJECT_ROOT/orchestrate
schedules:
- name: lastfm
  interval: '@daily'
  job: lastfm
  env:
    DBT_MODELS: +lastfm+
environments:
- name: prod
jobs:
- name: deploy
  tasks:
  - dbt-athena:deps
  - dbt-athena:run
- name: pipeline
  tasks:
  - tap-lastfm target-athena
  - tap-lichess target-athena
  - dbt-athena:run
  - dbt-athena:test
