version: 1
default_environment: local
send_anonymous_usage_stats: true
project_id: 7719d6c0-e1ea-45f2-85e4-a647da2211dd
plugins:
  extractors:
  - name: tap-lastfm
    namespace: tap_lastfm
    pip_url: git+https://github.com/rabidaudio/tap-lastfm.git@v0.1.1
    executable: tap-lastfm
    capabilities:
    - catalog
    - discover
    - state
    settings:
    - name: api_key
      kind: password
    - name: usernames
      kind: array
    - name: user_agent
      kind: string
    - name: start_date
      kind: date_iso8601
    config:
      api_key: $TAP_LASTFM_API_KEY
      usernames:
      - rabidaudio
      - kath_ebooks
      - valwigg
      - UntiLiUnderstan
      - trackstarlol
      - schwegler
      - emorphis
    select:
    - '*.*'
    - '!*.*image*'
  - name: tap-lichess
    namespace: tap_lichess
    pip_url: git+https://github.com/rabidaudio/tap-lichess.git@v1.0.0
    executable: tap-lichess
    capabilities:
    - catalog
    - discover
    - state
    settings:
    - name: auth_token
      kind: password
    - name: usernames
      kind: array
    config:
      usernames:
        - charlesjuliank
        - chuckbruckus
        - MaksimSundukov
        - LivAgar
        - Tom_Ripley
  loaders:
  - name: target-postgres
    variant: datamill-co
    pip_url: singer-target-postgres
  transformers:
  - name: dbt-postgres
    variant: dbt-labs
    pip_url: dbt-core~=1.0.0 dbt-postgres~=1.0.0
    commands:
      generate-source: run-operation generate_source --args ''{"schema_name":"$MELTANO_LOAD_SCHEMA","generate_columns":true}''
      test-freshness: source freshness
  utilities:
  - name: dagster
    namespace: dagster
    pip_url: -e orchestrate
    executable: dagster
    settings:
    - name: home
      env: DAGSTER_HOME
    - name: schedule_timezone
      env: DAGSTER_SCHEDULE_TIMEZONE
    - name: database_url
      env: DAGSTERDB_URL
    commands:
      scheduler:
        args: run -w $DAGSTER_HOME/workspace.yaml
        executable: dagster-daemon
      ui:
        args: -w $DAGSTER_HOME/workspace.yaml -h 0.0.0.0
        executable: dagit
      test:
        args: -v
        executable: pytest
    config:
      schedule_timezone: America/New_York
      database_url: $DAGSTERDB_URL
      home: $MELTANO_PROJECT_ROOT/orchestrate
  - name: yoyo-postgres
    namespace: yoyo_postgres
    pip_url: yoyo-migrations==7.3.2 psycopg2~=2.9.1
    executable: yoyo
    settings:
    - name: database
      env: YOYO_POSTGRES_DATABASE_URL
    - name: subdir
      env: YOYO_POSTGRES_SUBDIR
      value: migrations
    commands:
      new-setup: new -m setup
      apply-setup: apply -m 'setup$'
      new-postrun: new -m postrun
      apply-postrun: apply -m 'postrun$'
  - name: sqlfluff
    variant: sqlfluff
    pip_url: sqlfluff~=0.13.2 sqlfluff-templater-dbt~=0.13.2 dbt-postgres~=1.0.0
    commands:
      fix: fix
schedules:
- name: lastfm
  interval: '@daily'
  job: lastfm
  env:
    DBT_MODELS: +lastfm+
environments:
- name: local
  config:
    plugins:
      extractors:
      - name: tap-lastfm
        config:
          start_date: '2022-06-01'
          usernames:
          - rabidaudio
          - kath_ebooks
      loaders:
      - name: target-postgres
        config:
          postgres_host: $WAREHOUSE_HOST
          postgres_database: $WAREHOUSE_DBNAME
      transformers:
      - name: dbt-postgres
        config:
          host: $WAREHOUSE_HOST
          dbname: $WAREHOUSE_DBNAME
          schema: public
      utilities:
      - name: yoyo-postgres
        config:
          database: $WAREHOUSE_URL
  env:
    DAGSTERDB_URL: postgresql://localhost:5432/dagster
    WAREHOUSE_URL: postgresql://localhost:5432/selfdata
    WAREHOUSE_HOST: localhost
    WAREHOUSE_DBNAME: selfdata
jobs:
- name: deploy
  tasks:
  - dbt-postgres:deps yoyo-postgres:apply-setup
  - dbt-postgres:run
- name: pipeline
  tasks:
  - tap-lastfm target-postgres
  - tap-lichess target-postgres
  - yoyo-postgres:apply-postrun
  - dbt-postgres:run
  - dbt-postgres:test
