# Postgres config reference:
config:
  send_anonymous_usage_stats: False
  use_colors: True
meltano:
  target: "{{ env_var('MELTANO_ENVIRONMENT', 'local') }}"
  outputs:
    prod:
      type: athena
      database: awsdatacatalog
      s3_staging_dir: "s3://{{ env_var('WAREHOUSE_BUCKET') }}/dbt/"
      region_name: "{{ env_var('WAREHOUSE_REGION') }}"
      schema: analytics
